#ifndef DASHBOARD_PAGE_H
#define DASHBOARD_PAGE_H

static const char DASHBOARD_PAGE_HTML[] =
"<!doctype html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>ESP32-S3 Wi-Fi Sensing</title>"
"<style>"
":root{color-scheme:dark;--bg:#07111f;--panel:#0d1b2d;--line:#203550;--text:#e8f0fb;--muted:#8fa6c2;--green:#36d399;--blue:#60a5fa;--warn:#f6c453;--bad:#fb7185}"
"*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#102743 0,#07111f 48%);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,sans-serif}"
"main{width:min(1180px,calc(100% - 28px));margin:28px auto 48px}"
"header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:20px}"
"h1{font-size:clamp(24px,4vw,38px);margin:0 0 7px}p{margin:0;color:var(--muted)}"
".actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:flex-end}"
".badge,button{display:flex;align-items:center;gap:8px;padding:9px 13px;border:1px solid var(--line);background:#0a1728;color:var(--text);border-radius:999px;white-space:nowrap}"
"button{cursor:pointer}button:hover{border-color:var(--blue)}button:disabled{opacity:.55;cursor:not-allowed}"
".dot{width:10px;height:10px;border-radius:50%;background:var(--warn);box-shadow:0 0 14px currentColor}.dot.ok{background:var(--green)}.dot.bad{background:var(--bad)}"
".cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}"
".card,.chart-card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(16,36,60,.96),rgba(10,24,41,.96));border-radius:16px;box-shadow:0 14px 38px rgba(0,0,0,.22)}"
".card{padding:15px;min-height:98px}.label{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.value{font-size:23px;font-weight:700;margin-top:9px;overflow:hidden;text-overflow:ellipsis}.small{font-size:16px}"
".moving{color:var(--bad)}.static{color:var(--green)}.calibrating{color:var(--warn)}"
".charts{display:grid;grid-template-columns:1fr;gap:16px}.chart-card{padding:18px}.chart-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.chart-title{font-weight:700;font-size:18px}.range{color:var(--muted);font-size:13px}"
"canvas{display:block;width:100%;height:280px;border-radius:12px;background:#071321}"
"footer{margin-top:14px;color:var(--muted);font-size:13px;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}"
"@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}"
"@media(max-width:540px){main{width:min(100% - 18px,1180px);margin-top:18px}header{display:block}.actions{margin-top:14px;justify-content:flex-start}.cards{grid-template-columns:1fr}canvas{height:250px}}"
"</style>"
"</head>"
"<body>"
"<main>"
"<header><div><h1>ESP32-S3 Wi-Fi Sensing</h1><p>On-device CSI motion detection</p></div><div class=\"actions\"><button id=\"calibrateButton\" type=\"button\">Recalibrate</button><div class=\"badge\"><span id=\"wsDot\" class=\"dot\"></span><span id=\"wsText\">Connecting</span></div></div></header>"
"<section class=\"cards\">"
"<article class=\"card\"><div class=\"label\">Room state</div><div id=\"motionState\" class=\"value calibrating\">WARMUP</div></article>"
"<article class=\"card\"><div class=\"label\">Motion score</div><div id=\"motionScore\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">High threshold</div><div id=\"highThreshold\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Calibration</div><div id=\"calibration\" class=\"value\">0%</div></article>"
"<article class=\"card\"><div class=\"label\">Fast change</div><div id=\"fastChange\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Window activity</div><div id=\"windowActivity\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Baseline distance</div><div id=\"baselineDistance\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">CSI mean power</div><div id=\"csiPower\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">RSSI</div><div id=\"rssi\" class=\"value\">-- dBm</div></article>"
"<article class=\"card\"><div class=\"label\">Received packets</div><div id=\"received\" class=\"value\">0</div></article>"
"<article class=\"card\"><div class=\"label\">Dropped queue samples</div><div id=\"dropped\" class=\"value\">0</div></article>"
"<article class=\"card\"><div class=\"label\">Invalid CSI packets</div><div id=\"invalid\" class=\"value\">0</div></article>"
"<article class=\"card\"><div class=\"label\">Valid subcarriers</div><div id=\"valid\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Channel</div><div id=\"channel\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">SSID</div><div id=\"ssid\" class=\"value small\">--</div></article>"
"<article class=\"card\"><div class=\"label\">ESP32 IP</div><div id=\"ip\" class=\"value small\">--</div></article>"
"</section>"
"<section class=\"charts\">"
"<article class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">Motion score</div><div class=\"range\">Score · high threshold · low threshold</div></div><canvas id=\"motionChart\"></canvas></article>"
"<article class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">Motion features</div><div class=\"range\">Fast change · window activity · baseline distance</div></div><canvas id=\"featureChart\"></canvas></article>"
"<article class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">CSI mean power</div><div class=\"range\">Relative units</div></div><canvas id=\"csiChart\"></canvas></article>"
"</section>"
"<footer><span id=\"sampleInfo\">Waiting for CSI samples</span><span>HTTP + WebSocket · processing runs on ESP32</span></footer>"
"</main>"
"<script>"
"const MAX_POINTS=240;const motionPoints=[];const highPoints=[];const lowPoints=[];const fastPoints=[];const windowPoints=[];const baselinePoints=[];const csiPoints=[];let socket=null;let reconnectTimer=null;"
"const $=id=>document.getElementById(id);const motionCanvas=$('motionChart');const featureCanvas=$('featureChart');const csiCanvas=$('csiChart');"
"function setWs(state,text){$('wsDot').className='dot '+state;$('wsText').textContent=text;}"
"function resizeCanvas(canvas){const dpr=Math.max(1,window.devicePixelRatio||1),rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);canvas.getContext('2d').setTransform(dpr,0,0,dpr,0,0);}"
"function valueRange(first,second,third){const all=first.concat(second,third).filter(Number.isFinite);if(all.length===0)return[0,1];let lo=Math.min.apply(null,all),hi=Math.max.apply(null,all);lo=Math.min(0,lo);if(lo===hi)hi=lo+1;else{const pad=(hi-lo)*.12;hi+=pad;}return[lo,hi];}"
"function drawSeries(ctx,values,w,h,p,yMin,yMax,color){if(values.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();values.forEach((value,index)=>{const x=p.l+index*(w-p.l-p.r)/(MAX_POINTS-1),bounded=Math.max(yMin,Math.min(yMax,value)),y=p.t+(yMax-bounded)*(h-p.t-p.b)/(yMax-yMin);if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}"
"function drawChart(canvas,first,second,third,yMin,yMax,firstColor,secondColor,thirdColor,formatter){const ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=canvas.clientHeight,p={l:72,r:16,t:18,b:28};ctx.clearRect(0,0,w,h);ctx.fillStyle='#071321';ctx.fillRect(0,0,w,h);ctx.font='12px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';for(let i=0;i<=4;i++){const value=yMax-(yMax-yMin)*i/4,y=p.t+(h-p.t-p.b)*i/4;ctx.strokeStyle='#19304a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillStyle='#7891ad';ctx.fillText(formatter(value),p.l-8,y);}drawSeries(ctx,third,w,h,p,yMin,yMax,thirdColor);drawSeries(ctx,second,w,h,p,yMin,yMax,secondColor);drawSeries(ctx,first,w,h,p,yMin,yMax,firstColor);}"
"function draw(){let range=valueRange(motionPoints,highPoints,lowPoints);drawChart(motionCanvas,motionPoints,highPoints,lowPoints,range[0],range[1],'#fb7185','#f6c453','#94a3b8',v=>v.toFixed(2));range=valueRange(fastPoints,windowPoints,baselinePoints);drawChart(featureCanvas,fastPoints,windowPoints,baselinePoints,range[0],range[1],'#60a5fa','#36d399','#c084fc',v=>v.toFixed(2));range=valueRange(csiPoints,[],[]);drawChart(csiCanvas,csiPoints,[],[],range[0],range[1],'#60a5fa','#60a5fa','#60a5fa',v=>v.toFixed(0));}"
"function resize(){resizeCanvas(motionCanvas);resizeCanvas(featureCanvas);resizeCanvas(csiCanvas);draw();}"
"function pushPoint(array,value){array.push(value);if(array.length>MAX_POINTS)array.shift();}"
"function setMotionState(state){const element=$('motionState');element.textContent=state;element.className='value '+(state==='MOVING'?'moving':state==='STATIC'?'static':'calibrating');}"
"function addSample(s){if(s.type!=='csi'||typeof s.motion_score!=='number')return;pushPoint(motionPoints,s.motion_score);pushPoint(highPoints,s.threshold_high);pushPoint(lowPoints,s.threshold_low);pushPoint(fastPoints,s.fast_change);pushPoint(windowPoints,s.window_activity);pushPoint(baselinePoints,s.baseline_distance);pushPoint(csiPoints,s.mean_power);setMotionState(s.motion_state);$('motionScore').textContent=s.motion_score.toFixed(3);$('highThreshold').textContent=s.calibrated?s.threshold_high.toFixed(3):'--';$('calibration').textContent=s.calibration_progress+'%';$('fastChange').textContent=s.fast_change.toFixed(3);$('windowActivity').textContent=s.window_activity.toFixed(3);$('baselineDistance').textContent=s.baseline_distance.toFixed(3);$('csiPower').textContent=s.mean_power.toFixed(1);$('rssi').textContent=s.rssi+' dBm';$('received').textContent=s.received;$('dropped').textContent=s.dropped;$('invalid').textContent=s.invalid;$('valid').textContent=s.valid;$('channel').textContent=s.channel;$('sampleInfo').textContent='CSI sample '+s.seq+' · '+motionPoints.length+' browser points';draw();}"
"function connectWs(){clearTimeout(reconnectTimer);const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(protocol+'//'+location.host+'/ws');setWs('','Connecting');socket.onopen=()=>setWs('ok','Live');socket.onmessage=event=>{try{addSample(JSON.parse(event.data));}catch(error){}};socket.onerror=()=>socket.close();socket.onclose=()=>{setWs('bad','Disconnected');reconnectTimer=setTimeout(connectWs,1500);};}"
"async function updateStatus(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw new Error();const s=await response.json();$('ssid').textContent=s.ssid||'--';$('ip').textContent=s.ip||'--';$('channel').textContent=(s.channel===undefined)?'--':s.channel;}catch(error){$('ip').textContent='Unavailable';}}"
"async function recalibrate(){const button=$('calibrateButton');button.disabled=true;try{const response=await fetch('/api/calibrate',{method:'POST',cache:'no-store'});if(!response.ok)throw new Error();motionPoints.length=0;highPoints.length=0;lowPoints.length=0;fastPoints.length=0;windowPoints.length=0;baselinePoints.length=0;csiPoints.length=0;setMotionState('WARMUP');$('calibration').textContent='0%';}catch(error){alert('Cannot start calibration');}finally{setTimeout(()=>{button.disabled=false;},1000);}}"
"$('calibrateButton').addEventListener('click',recalibrate);window.addEventListener('resize',resize);resize();connectWs();updateStatus();setInterval(updateStatus,2000);"
"</script>"
"</body>"
"</html>";

#endif
