#ifndef DASHBOARD_PAGE_H
#define DASHBOARD_PAGE_H

static const char DASHBOARD_PAGE_HTML[] =
"<!doctype html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>ESP32-S3 Wi-Fi Sensing</title>"
"<style>"
":root{color-scheme:dark;--bg:#07111f;--panel:#0d1b2d;--line:#203550;--text:#e8f0fb;--muted:#8fa6c2;--accent:#36d399;--warn:#f6c453;--bad:#fb7185}"
"*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#102743 0,#07111f 48%);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,sans-serif}"
"main{width:min(1120px,calc(100% - 28px));margin:28px auto 48px}"
"header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:20px}"
"h1{font-size:clamp(24px,4vw,38px);margin:0 0 7px}p{margin:0;color:var(--muted)}"
".badge{display:flex;align-items:center;gap:8px;padding:9px 13px;border:1px solid var(--line);background:#0a1728;border-radius:999px;white-space:nowrap}"
".dot{width:10px;height:10px;border-radius:50%;background:var(--warn);box-shadow:0 0 14px currentColor}.dot.ok{background:var(--accent)}.dot.bad{background:var(--bad)}"
".cards{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:16px}"
".card,.chart-card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(16,36,60,.96),rgba(10,24,41,.96));border-radius:16px;box-shadow:0 14px 38px rgba(0,0,0,.22)}"
".card{padding:16px;min-height:104px}.label{font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}.value{font-size:24px;font-weight:720;margin-top:10px;overflow:hidden;text-overflow:ellipsis}.small{font-size:17px}"
".chart-card{padding:18px}.chart-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.chart-title{font-weight:700;font-size:18px}.range{color:var(--muted);font-size:13px}"
"canvas{display:block;width:100%;height:390px;border-radius:12px;background:#071321}"
"footer{margin-top:14px;color:var(--muted);font-size:13px;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}"
"@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.card:last-child{grid-column:span 2}}"
"@media(max-width:540px){main{width:min(100% - 18px,1120px);margin-top:18px}header{display:block}.badge{margin-top:14px;width:max-content}.cards{grid-template-columns:1fr}.card:last-child{grid-column:auto}canvas{height:320px}}"
"</style>"
"</head>"
"<body>"
"<main>"
"<header><div><h1>ESP32-S3 Wi-Fi Sensing</h1><p>M4 · Live RSSI telemetry over WebSocket</p></div><div class=\"badge\"><span id=\"wsDot\" class=\"dot\"></span><span id=\"wsText\">Connecting</span></div></header>"
"<section class=\"cards\">"
"<article class=\"card\"><div class=\"label\">RSSI</div><div id=\"rssi\" class=\"value\">-- dBm</div></article>"
"<article class=\"card\"><div class=\"label\">SSID</div><div id=\"ssid\" class=\"value small\">--</div></article>"
"<article class=\"card\"><div class=\"label\">ESP32 IP</div><div id=\"ip\" class=\"value small\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Channel</div><div id=\"channel\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Uptime</div><div id=\"uptime\" class=\"value small\">--</div></article>"
"</section>"
"<section class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">RSSI history</div><div class=\"range\">-100 to -20 dBm · latest 240 samples</div></div><canvas id=\"chart\"></canvas></section>"
"<footer><span id=\"sampleInfo\">Waiting for samples</span><span>HTTP + WebSocket · no external CDN</span></footer>"
"</main>"
"<script>"
"const MAX_POINTS=240,Y_MIN=-100,Y_MAX=-20;"
"const points=[];let socket=null,reconnectTimer=null;"
"const canvas=document.getElementById('chart'),ctx=canvas.getContext('2d');"
"const $=id=>document.getElementById(id);"
"function setWs(state,text){$('wsDot').className='dot '+state;$('wsText').textContent=text;}"
"function resize(){const dpr=Math.max(1,window.devicePixelRatio||1);const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}"
"function draw(){const w=canvas.clientWidth,h=canvas.clientHeight,p={l:52,r:16,t:18,b:32};ctx.clearRect(0,0,w,h);ctx.fillStyle='#071321';ctx.fillRect(0,0,w,h);ctx.font='12px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';for(let y=Y_MIN;y<=Y_MAX;y+=10){const py=p.t+(Y_MAX-y)*(h-p.t-p.b)/(Y_MAX-Y_MIN);ctx.strokeStyle='#19304a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.l,py);ctx.lineTo(w-p.r,py);ctx.stroke();ctx.fillStyle='#7891ad';ctx.fillText(y+' dBm',p.l-8,py);}if(points.length<2)return;ctx.strokeStyle='#36d399';ctx.lineWidth=2;ctx.beginPath();points.forEach((v,i)=>{const x=p.l+i*(w-p.l-p.r)/(MAX_POINTS-1);const clamped=Math.max(Y_MIN,Math.min(Y_MAX,v.rssi));const y=p.t+(Y_MAX-clamped)*(h-p.t-p.b)/(Y_MAX-Y_MIN);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();const last=points[points.length-1];const lx=p.l+(points.length-1)*(w-p.l-p.r)/(MAX_POINTS-1);const ly=p.t+(Y_MAX-Math.max(Y_MIN,Math.min(Y_MAX,last.rssi)))*(h-p.t-p.b)/(Y_MAX-Y_MIN);ctx.fillStyle='#36d399';ctx.beginPath();ctx.arc(lx,ly,4,0,Math.PI*2);ctx.fill();}"
"function addSample(s){if(typeof s.rssi!=='number')return;points.push(s);if(points.length>MAX_POINTS)points.shift();$('rssi').textContent=s.rssi+' dBm';$('channel').textContent=s.channel;$('sampleInfo').textContent='Sample '+s.seq+' · '+points.length+' points buffered';draw();}"
"function connectWs(){clearTimeout(reconnectTimer);const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(protocol+'//'+location.host+'/ws');setWs('','Connecting');socket.onopen=()=>setWs('ok','Live');socket.onmessage=e=>{try{addSample(JSON.parse(e.data));}catch(_){}};socket.onerror=()=>socket.close();socket.onclose=()=>{setWs('bad','Disconnected');reconnectTimer=setTimeout(connectWs,1500);};}"
"function formatUptime(ms){let s=Math.floor(ms/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;return(d?d+'d ':'')+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}"
"async function updateStatus(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw new Error();const s=await response.json();$('ssid').textContent=s.ssid||'--';$('ip').textContent=s.ip||'--';$('channel').textContent=(s.channel==null?'--':s.channel);$('uptime').textContent=formatUptime(s.uptime_ms||0);if(points.length===0&&typeof s.rssi==='number')$('rssi').textContent=s.rssi+' dBm';}catch(_){$('ip').textContent='Unavailable';}}"
"window.addEventListener('resize',resize);resize();connectWs();updateStatus();setInterval(updateStatus,2000);"
"</script>"
"</body>"
"</html>";

#endif