#ifndef DASHBOARD_PAGE_H
#define DASHBOARD_PAGE_H

static const char DASHBOARD_PAGE_HTML[] =
"<!doctype html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>ESP32-S3 CSI Monitor</title>"
"<style>"
":root{color-scheme:dark;--bg:#07111f;--panel:#0d1b2d;--line:#203550;--text:#e8f0fb;--muted:#8fa6c2;--green:#36d399;--blue:#60a5fa;--warn:#f6c453;--bad:#fb7185}"
"*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#102743 0,#07111f 48%);color:var(--text);font-family:system-ui,-apple-system,Segoe UI,sans-serif}"
"main{width:min(1180px,calc(100% - 28px));margin:28px auto 48px}"
"header{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:20px}"
"h1{font-size:clamp(24px,4vw,38px);margin:0 0 7px}p{margin:0;color:var(--muted)}"
".badge{display:flex;align-items:center;gap:8px;padding:9px 13px;border:1px solid var(--line);background:#0a1728;border-radius:999px;white-space:nowrap}"
".dot{width:10px;height:10px;border-radius:50%;background:var(--warn);box-shadow:0 0 14px currentColor}.dot.ok{background:var(--green)}.dot.bad{background:var(--bad)}"
".cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}"
".card,.chart-card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(16,36,60,.96),rgba(10,24,41,.96));border-radius:16px;box-shadow:0 14px 38px rgba(0,0,0,.22)}"
".card{padding:15px;min-height:98px}.label{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.value{font-size:23px;font-weight:700;margin-top:9px;overflow:hidden;text-overflow:ellipsis}.small{font-size:16px}"
".charts{display:grid;grid-template-columns:1fr;gap:16px}.chart-card{padding:18px}.chart-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.chart-title{font-weight:700;font-size:18px}.range{color:var(--muted);font-size:13px}"
"canvas{display:block;width:100%;height:300px;border-radius:12px;background:#071321}"
"footer{margin-top:14px;color:var(--muted);font-size:13px;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}"
"@media(max-width:850px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}"
"@media(max-width:540px){main{width:min(100% - 18px,1180px);margin-top:18px}header{display:block}.badge{margin-top:14px;width:max-content}.cards{grid-template-columns:1fr}canvas{height:260px}}"
"</style>"
"</head>"
"<body>"
"<main>"
"<header><div><h1>ESP32-S3 Wi-Fi CSI</h1><p>M5 · LLTF CSI acquisition and on-device processing</p></div><div class=\"badge\"><span id=\"wsDot\" class=\"dot\"></span><span id=\"wsText\">Connecting</span></div></header>"
"<section class=\"cards\">"
"<article class=\"card\"><div class=\"label\">CSI mean power</div><div id=\"csiPower\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">RSSI</div><div id=\"rssi\" class=\"value\">-- dBm</div></article>"
"<article class=\"card\"><div class=\"label\">Received packets</div><div id=\"received\" class=\"value\">0</div></article>"
"<article class=\"card\"><div class=\"label\">Dropped packets</div><div id=\"dropped\" class=\"value\">0</div></article>"
"<article class=\"card\"><div class=\"label\">Valid subcarriers</div><div id=\"valid\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">Channel</div><div id=\"channel\" class=\"value\">--</div></article>"
"<article class=\"card\"><div class=\"label\">SSID</div><div id=\"ssid\" class=\"value small\">--</div></article>"
"<article class=\"card\"><div class=\"label\">ESP32 IP</div><div id=\"ip\" class=\"value small\">--</div></article>"
"</section>"
"<section class=\"charts\">"
"<article class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">CSI mean power</div><div class=\"range\">Relative units · auto scale</div></div><canvas id=\"csiChart\"></canvas></article>"
"<article class=\"chart-card\"><div class=\"chart-head\"><div class=\"chart-title\">RSSI history</div><div class=\"range\">-100 to -20 dBm</div></div><canvas id=\"rssiChart\"></canvas></article>"
"</section>"
"<footer><span id=\"sampleInfo\">Waiting for CSI samples</span><span>HTTP + WebSocket · no external CDN</span></footer>"
"</main>"
"<script>"
"const MAX_POINTS=240;const csiPoints=[];const rssiPoints=[];let socket=null;let reconnectTimer=null;"
"const $=id=>document.getElementById(id);const csiCanvas=$('csiChart');const rssiCanvas=$('rssiChart');"
"function setWs(state,text){$('wsDot').className='dot '+state;$('wsText').textContent=text;}"
"function resizeCanvas(canvas){const dpr=Math.max(1,window.devicePixelRatio||1);const rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);canvas.getContext('2d').setTransform(dpr,0,0,dpr,0,0);}"
"function csiRange(){if(csiPoints.length===0)return[0,1];let lo=Math.min.apply(null,csiPoints),hi=Math.max.apply(null,csiPoints);if(lo===hi){const pad=Math.max(1,Math.abs(lo)*.05);lo-=pad;hi+=pad;}else{const pad=(hi-lo)*.1;lo-=pad;hi+=pad;}return[lo,hi];}"
"function drawChart(canvas,values,yMin,yMax,color,formatValue){const ctx=canvas.getContext('2d'),w=canvas.clientWidth,h=canvas.clientHeight,p={l:68,r:16,t:18,b:28};ctx.clearRect(0,0,w,h);ctx.fillStyle='#071321';ctx.fillRect(0,0,w,h);ctx.font='12px system-ui';ctx.textAlign='right';ctx.textBaseline='middle';for(let i=0;i<=4;i++){const value=yMax-(yMax-yMin)*i/4;const y=p.t+(h-p.t-p.b)*i/4;ctx.strokeStyle='#19304a';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillStyle='#7891ad';ctx.fillText(formatValue(value),p.l-8,y);}if(values.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();values.forEach((value,index)=>{const x=p.l+index*(w-p.l-p.r)/(MAX_POINTS-1);const bounded=Math.max(yMin,Math.min(yMax,value));const y=p.t+(yMax-bounded)*(h-p.t-p.b)/(yMax-yMin);if(index===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();}"
"function draw(){const range=csiRange();drawChart(csiCanvas,csiPoints,range[0],range[1],'#60a5fa',v=>v.toFixed(0));drawChart(rssiCanvas,rssiPoints,-100,-20,'#36d399',v=>v.toFixed(0)+' dBm');}"
"function resize(){resizeCanvas(csiCanvas);resizeCanvas(rssiCanvas);draw();}"
"function addSample(s){if(s.type!=='csi'||typeof s.mean_power!=='number')return;csiPoints.push(s.mean_power);rssiPoints.push(s.rssi);if(csiPoints.length>MAX_POINTS)csiPoints.shift();if(rssiPoints.length>MAX_POINTS)rssiPoints.shift();$('csiPower').textContent=s.mean_power.toFixed(1);$('rssi').textContent=s.rssi+' dBm';$('received').textContent=s.received;$('dropped').textContent=s.dropped;$('valid').textContent=s.valid;$('channel').textContent=s.channel;$('sampleInfo').textContent='CSI sample '+s.seq+' · '+csiPoints.length+' points buffered';draw();}"
"function connectWs(){clearTimeout(reconnectTimer);const protocol=location.protocol==='https:'?'wss:':'ws:';socket=new WebSocket(protocol+'//'+location.host+'/ws');setWs('','Connecting');socket.onopen=()=>setWs('ok','Live');socket.onmessage=event=>{try{addSample(JSON.parse(event.data));}catch(error){}};socket.onerror=()=>socket.close();socket.onclose=()=>{setWs('bad','Disconnected');reconnectTimer=setTimeout(connectWs,1500);};}"
"async function updateStatus(){try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw new Error();const s=await response.json();$('ssid').textContent=s.ssid||'--';$('ip').textContent=s.ip||'--';$('channel').textContent=(s.channel===undefined)?'--':s.channel;if(csiPoints.length===0&&typeof s.rssi==='number')$('rssi').textContent=s.rssi+' dBm';}catch(error){$('ip').textContent='Unavailable';}}"
"window.addEventListener('resize',resize);resize();connectWs();updateStatus();setInterval(updateStatus,2000);"
"</script>"
"</body>"
"</html>";

#endif
