#ifndef PROVISIONING_WEB_H
#define PROVISIONING_WEB_H

static const char PROVISIONING_HTML[] =
    "<!DOCTYPE html>"
    "<html lang=\"en\">"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" "
    "content=\"width=device-width,initial-scale=1\">"
    "<title>ESP32 Wi-Fi Setup</title>"
    "<style>"
    "body{"
        "font-family:Arial,sans-serif;"
        "background:#0f172a;"
        "color:#e2e8f0;"
        "margin:0;"
        "min-height:100vh;"
        "display:flex;"
        "align-items:center;"
        "justify-content:center;"
    "}"
    ".card{"
        "width:min(92%,420px);"
        "background:#1e293b;"
        "padding:28px;"
        "border-radius:16px;"
        "box-shadow:0 16px 40px rgba(0,0,0,.35);"
    "}"
    "h1{margin-top:0;font-size:24px;}"
    "p{color:#94a3b8;line-height:1.5;}"
    "label{display:block;margin:16px 0 6px;}"
    "input{"
        "width:100%;"
        "box-sizing:border-box;"
        "padding:12px;"
        "border-radius:8px;"
        "border:1px solid #475569;"
        "background:#0f172a;"
        "color:#fff;"
    "}"
    "button{"
        "width:100%;"
        "margin-top:18px;"
        "padding:12px;"
        "border:0;"
        "border-radius:8px;"
        "background:#22c55e;"
        "font-weight:bold;"
        "cursor:pointer;"
    "}"
    "#scan{background:#38bdf8;margin-top:10px;}"
    "#status{margin-top:12px;color:#fbbf24;}"
    "</style>"
    "</head>"
    "<body>"
    "<div class=\"card\">"
    "<h1>ESP32-S3 Wi-Fi Setup</h1>"
    "<p>Select or enter a 2.4 GHz Wi-Fi network.</p>"

    "<button id=\"scan\" type=\"button\" "
    "onclick=\"scanNetworks()\">Scan Wi-Fi</button>"

    "<div id=\"status\"></div>"

    "<form method=\"POST\" action=\"/api/config\">"
    "<label for=\"ssid\">SSID</label>"
    "<input id=\"ssid\" name=\"ssid\" "
    "list=\"network-list\" maxlength=\"32\" required>"
    "<datalist id=\"network-list\"></datalist>"

    "<label for=\"password\">Password</label>"
    "<input id=\"password\" name=\"password\" "
    "type=\"password\" maxlength=\"64\">"

    "<button type=\"submit\">Save and Connect</button>"
    "</form>"
    "</div>"

    "<script>"
    "async function scanNetworks(){"
        "const status=document.getElementById('status');"
        "const list=document.getElementById('network-list');"
        "status.textContent='Scanning...';"
        "list.innerHTML='';"
        "try{"
            "const response=await fetch('/api/scan');"
            "if(!response.ok)throw new Error('scan failed');"
            "const networks=await response.json();"
            "networks.forEach(network=>{"
                "const option=document.createElement('option');"
                "option.value=network.ssid;"
                "option.textContent="
                    "network.ssid+' ('+network.rssi+' dBm)';"
                "list.appendChild(option);"
            "});"
            "status.textContent="
                "networks.length+' networks found';"
        "}catch(error){"
            "status.textContent='Unable to scan Wi-Fi';"
        "}"
    "}"
    "</script>"
    "</body>"
    "</html>";

static const char PROVISIONING_SUCCESS_HTML[] =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" "
    "content=\"width=device-width,initial-scale=1\">"
    "<title>Saved</title>"
    "</head>"
    "<body style=\"font-family:Arial;text-align:center;"
    "padding:40px;background:#0f172a;color:#e2e8f0\">"
    "<h1>Configuration saved</h1>"
    "<p>The ESP32 will restart and test the new network.</p>"
    "<p>If the connection fails, reconnect to the setup AP.</p>"
    "</body>"
    "</html>";

#endif /* PROVISIONING_WEB_H */